title: "Tanya Singh"
description: "Software Engineer • Java • Python • Spring Boot • FastAPI • DevOps"
theme: minima
author:
  name: "Tanya Singh"
  email: "tanyasinghofficial25@gmail.com"
  phone: "+91 7400399430"
  location: "Mumbai, India"

# Social links
linkedin_username: tanya-singh-3b891b1b2
github_username: Tanya683
twitter_username: null

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
